config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :kittens
  root "kittens#index"

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  validates :name, :age, :cuteness, :softness, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  before_action :set_kitten, only: %i[ show edit update destroy]
  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.html
      format.json { render json: @kittens }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(allowed_kittens_params)

    if @kitten.save
      redirect_to @kitten, notice: "Created succsessfully"
    else
      flash[:notice] = "Failed to create, #{ @kitten.errors.full_messages }"
      render :new, status: :unprocessable_entity
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json { render json: @kitten }
    end
  end

  def edit
  end

  def update
    if @kitten.update(allowed_kittens_params)
      redirect_to @kitten, notice: "Updated succsessfully"
    else
      flash[:notice] = "Failed to update, #{ @kitten.errors.full_messages }"
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @kitten.destroy

    redirect_to kittens_path
  end

  private

  def set_kitten
    @kitten = Kitten.find(params[:id])
  end

  def allowed_kittens_params
    params.expect(kitten: [ :name, :age, :cuteness, :softness ])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_flash.html.erb
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

app/views/kittens/_form.html.erb
<%= form_with model: @kitten do |form| %>
    <div>
        <%= form.label :name %>
        <%= form.text_field :name %>
    </div>
    <div>
        <%= form.label :age %>
        <%= form.number_field :age %>
    </div>
    <div>
        <%= form.label :cuteness %>
        <%= form.select :cuteness, options_for_select(1..10) %>
    </div>
    <div>
        <%= form.label :softness %>
        <%= form.select :softness, options_for_select(1..10) %>
    </div>
    <div>
    <%= form.submit %>
    </div>
<% end %>

app/views/kittens/edit.html.erb
<%= render "flash" %>
<%= render "form" %>

app/views/kittens/index.html.erb
<%= render "flash" %>
<%= button_to "Create Kitten", new_kitten_path, method: :get %>

<% @kittens.each do |kitten| %>
    <h1> <%= kitten.name %> </h1>
    <ul>
        <li><%= "Age: #{kitten.age}" %></li>
        <li><%= "Cuteness: #{kitten.cuteness}" %></li>
        <li><%= "Softness: #{kitten.softness}" %></li>
    </ul>
    <div style="display: inline-grid; grid-template-columns: auto auto; grid-gap: 1rem;">
        <%= button_to "Edit #{ kitten.name }", edit_kitten_path(kitten), { :method => :get } %>
        <%= button_to "Delete", kitten, method: :delete, data: { turbo_confirm: "Are you sure?" } %>
    </div>
<% end %>

app/views/kittens/new.html.erb
<%= render "flash" %>
<%= render "form" %>

app/views/kittens/show.html.erb
<%= render "flash" %>
<h1> <%= @kitten.name %> </h1>
<ul>
    <li><%= "Age: #{ @kitten.age }" %></li>
    <li><%= "Cuteness: #{ @kitten.cuteness }" %></li>
    <li><%= "Softness: #{ @kitten.softness }" %></li>
</ul>
<div style="display: inline-grid; grid-template-columns: auto auto auto; grid-gap: 1rem;">
    <%= button_to "Edit #{ @kitten.name }", edit_kitten_path(@kitten), { :method => :get } %>
    <%= button_to "Delete", @kitten, method: :delete, data: { turbo_confirm: "Are you sure?" } %>
    <%= button_to "Home", kittens_path, { :method => :get } %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Odin Kittens" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>